version: '3.9'

services:
  backend:
    build:
      context: ./
      args:
        # Build time arguments
        APP_NAME: ${APP_NAME}
        APP_PORT: ${APP_PORT}
        REBAR_PROFILE: ${REBAR_PROFILE}
    hostname: x11_sentinel_server_${RUNTIME_ENV}_1
    restart: unless-stopped
    environment:
    # Common variables
    - APP_NAME
    - APP_PORT
    # Build time variables
    - REBAR_PROFILE
    # Runtime variables
    - APP_DB_HOST
    - APP_DB_USERNAME
    - APP_DB_PASSWORD
    - APP_DB_PORT
    - APP_DB_NAME
    - APP_EVALUATION_SERVICE_HOST
    - APP_EVALUATION_SERVICE_PORT
    - APP_MINIMUM_ELAPSED_TIME_FOR_FAILED_PROFILE_REBUILD
    - APP_MINIMUM_EVENT_COUNT_FOR_VERIFICATION
    - APP_MINIMUM_EVENT_COUNT_FOR_PROFILE
    - APP_SECRET_COOKIE
    - NODE_NAME
    - RUNTIME_ENV
    networks:
    - x11_sentinel_server
    ports:
    - "${APP_PORT}:${APP_PORT}"
  db:
    image: postgres:11
    environment:
    # Runtime variables
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    networks:
     - x11_sentinel_server
    restart: unless-stopped
    volumes:
     - db-data:/var/lib/postgresql/data
  evaluation:
    build:
      context: ./evaluation/
      args:
        # Build time arguments
        EVALUATION_PORT: ${EVALUATION_PORT}
    restart: unless-stopped
    environment:
    # Common variables
    - EVALUATION_PORT
    # Runtime variables
    - EVALUATION_RESPONSE_DIR
    - EVALUATION_PROFILE_BUILD_WAIT_TIME
    - EVALUATION_VERIFY_WAIT_TIME
    networks:
    - x11_sentinel_server
    volumes:
    - evaluation-response-data:/srv/data

networks:
  x11_sentinel_server:
    driver: bridge
    external: true
    name: x11_sentinel_server

volumes:
  db-data:
  evaluation-response-data:
