DROP TABLE xss.users CASCADE;
DROP TABLE xss.sessions CASCADE;
DROP TABLE xss.streams CASCADE;
DROP TABLE xss.chunks CASCADE;
DROP TABLE xss.profiles CASCADE;
DROP TABLE xss.verifications CASCADE;

DROP SCHEMA xss CASCADE;
